#!/usr/bin/env bash
# Script that display the pid, along with the process name of processes
# whose name contain the word bash

pgrep -f bash | while read -r pid; do
    process_name=$(ps -p "$pid" -o comm=)
    echo "$pid $process_name"
done