#!/usr/bin/env bash
# script that kill 7-highlander process

pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    echo "Stopping the process with PID $pid"
    kill "$pid"
else
    echo "Process 7-highlander not found"
fi