#!/usr/bin/env bash
# script that Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds 

pid_file="/var/run/my_process.pid"
output_file="/tmp/my_process"

start_process() {
    if [ -f "$pid_file" ]; then
        echo "Process is already running. PID: $(cat "$pid_file")"
    else
        ./manage_my_process &
        echo $! > "$pid_file"
        echo "manage_my_process started"
    fi
}

stop_process() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        wait "$pid"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "No running process found."
    fi
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac