#!/usr/bin/env bash

# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

for hours in {0..12}; do
    for minutes in {1..59}; do
        echo "$hours:$minutes"
    done
done