#!/usr/bin/env bash

# Script that display the current directory in a list format

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        filename="${file#*-}"
        echo "$filename"
    fi
done